(* autogenerated from github.com/codyjrivera/heapexamples *)
From New.golang Require Import defn.
Module pkg_id.
Definition heapexamples : go_string := "github.com/codyjrivera/heapexamples".

End pkg_id.
Export pkg_id.
Module heapexamples.

Definition AVLNode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/codyjrivera/heapexamples.AVLNode"%go [].

#[global] Opaque AVLNode.

Definition TreeNode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/codyjrivera/heapexamples.TreeNode"%go [].

#[global] Opaque TreeNode.

Definition ListNode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/codyjrivera/heapexamples.ListNode"%go [].

#[global] Opaque ListNode.

Definition fromSlice {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/codyjrivera/heapexamples.fromSlice"%go.

(* go: avl.go:10:19 *)
Definition AVLNode__heightⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "n" <>,
    exception_do (let: "n" := (GoAlloc (go.PointerType AVLNode) "n") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType AVLNode] "n") =⟨go.PointerType AVLNode⟩ (Convert go.untyped_nil (go.PointerType AVLNode) UntypedNil))
    then return: (Convert go.untyped_int go.int (⟨go.untyped_int⟩- #1))
    else do:  #());;;
    return: (![go.int] (StructFieldRef AVLNode "Height"%go (![go.PointerType AVLNode] "n")))).

(* go: avl.go:17:19 *)
Definition AVLNode__updateHeightⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "n" <>,
    exception_do (let: "n" := (GoAlloc (go.PointerType AVLNode) "n") in
    let: "r" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "l" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := ((MethodResolve (go.PointerType AVLNode) "height"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "n")))) #()) in
    let: "$r1" := ((MethodResolve (go.PointerType AVLNode) "height"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "n")))) #()) in
    do:  ("l" <-[go.int] "$r0");;;
    do:  ("r" <-[go.int] "$r1");;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "l") >⟨go.int⟩ (![go.int] "r"))
    then
      let: "$r0" := ((![go.int] "l") +⟨go.int⟩ #(W64 1)) in
      do:  ((StructFieldRef AVLNode "Height"%go (![go.PointerType AVLNode] "n")) <-[go.int] "$r0")
    else
      let: "$r0" := ((![go.int] "r") +⟨go.int⟩ #(W64 1)) in
      do:  ((StructFieldRef AVLNode "Height"%go (![go.PointerType AVLNode] "n")) <-[go.int] "$r0"));;;
    return: #()).

(* go: avl.go:26:19 *)
Definition AVLNode__balanceFactorⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "n" <>,
    exception_do (let: "n" := (GoAlloc (go.PointerType AVLNode) "n") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType AVLNode] "n") =⟨go.PointerType AVLNode⟩ (Convert go.untyped_nil (go.PointerType AVLNode) UntypedNil))
    then return: (#(W64 0))
    else do:  #());;;
    return: (((MethodResolve (go.PointerType AVLNode) "height"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "n")))) #()) -⟨go.int⟩ ((MethodResolve (go.PointerType AVLNode) "height"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "n")))) #()))).

(* go: avl.go:33:19 *)
Definition AVLNode__rotateRightⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "n" <>,
    exception_do (let: "n" := (GoAlloc (go.PointerType AVLNode) "n") in
    let: "l" := (GoAlloc (go.PointerType AVLNode) (GoZeroVal (go.PointerType AVLNode) #())) in
    let: "$r0" := (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "n"))) in
    do:  ("l" <-[go.PointerType AVLNode] "$r0");;;
    let: "$r0" := (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "l"))) in
    do:  ((StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "n")) <-[go.PointerType AVLNode] "$r0");;;
    let: "$r0" := (![go.PointerType AVLNode] "n") in
    do:  ((StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "l")) <-[go.PointerType AVLNode] "$r0");;;
    do:  ((MethodResolve (go.PointerType AVLNode) "updateHeight"%go (![go.PointerType AVLNode] "n")) #());;;
    do:  ((MethodResolve (go.PointerType AVLNode) "updateHeight"%go (![go.PointerType AVLNode] "l")) #());;;
    return: (![go.PointerType AVLNode] "l")).

(* go: avl.go:42:19 *)
Definition AVLNode__rotateLeftⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "n" <>,
    exception_do (let: "n" := (GoAlloc (go.PointerType AVLNode) "n") in
    let: "r" := (GoAlloc (go.PointerType AVLNode) (GoZeroVal (go.PointerType AVLNode) #())) in
    let: "$r0" := (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "n"))) in
    do:  ("r" <-[go.PointerType AVLNode] "$r0");;;
    let: "$r0" := (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "r"))) in
    do:  ((StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "n")) <-[go.PointerType AVLNode] "$r0");;;
    let: "$r0" := (![go.PointerType AVLNode] "n") in
    do:  ((StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "r")) <-[go.PointerType AVLNode] "$r0");;;
    do:  ((MethodResolve (go.PointerType AVLNode) "updateHeight"%go (![go.PointerType AVLNode] "n")) #());;;
    do:  ((MethodResolve (go.PointerType AVLNode) "updateHeight"%go (![go.PointerType AVLNode] "r")) #());;;
    return: (![go.PointerType AVLNode] "r")).

(* go: avl.go:51:19 *)
Definition AVLNode__rebalanceⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "n" <>,
    exception_do (let: "n" := (GoAlloc (go.PointerType AVLNode) "n") in
    let: "bf" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := ((MethodResolve (go.PointerType AVLNode) "balanceFactor"%go (![go.PointerType AVLNode] "n")) #()) in
    do:  ("bf" <-[go.int] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "bf") >⟨go.int⟩ #(W64 1))
    then
      (if: Convert go.untyped_bool go.bool (((MethodResolve (go.PointerType AVLNode) "balanceFactor"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "n")))) #()) <⟨go.int⟩ #(W64 0))
      then
        let: "$r0" := ((MethodResolve (go.PointerType AVLNode) "rotateLeft"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "n")))) #()) in
        do:  ((StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "n")) <-[go.PointerType AVLNode] "$r0")
      else do:  #());;;
      return: ((MethodResolve (go.PointerType AVLNode) "rotateRight"%go (![go.PointerType AVLNode] "n")) #())
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "bf") <⟨go.int⟩ (Convert go.untyped_int go.int (⟨go.untyped_int⟩- #1)))
    then
      (if: Convert go.untyped_bool go.bool (((MethodResolve (go.PointerType AVLNode) "balanceFactor"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "n")))) #()) >⟨go.int⟩ #(W64 0))
      then
        let: "$r0" := ((MethodResolve (go.PointerType AVLNode) "rotateRight"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "n")))) #()) in
        do:  ((StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "n")) <-[go.PointerType AVLNode] "$r0")
      else do:  #());;;
      return: ((MethodResolve (go.PointerType AVLNode) "rotateLeft"%go (![go.PointerType AVLNode] "n")) #())
    else do:  #());;;
    return: (![go.PointerType AVLNode] "n")).

(* go: avl.go:68:19 *)
Definition AVLNode__avlMinⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "n" <>,
    exception_do (let: "n" := (GoAlloc (go.PointerType AVLNode) "n") in
    (for: (λ: <>, (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "n"))) ≠⟨go.PointerType AVLNode⟩ (Convert go.untyped_nil (go.PointerType AVLNode) UntypedNil)); (λ: <>, #()) := λ: <>,
      let: "$r0" := (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "n"))) in
      do:  ("n" <-[go.PointerType AVLNode] "$r0"));;;
    return: (![go.PointerType AVLNode] "n")).

(* go: avl.go:75:22 *)
Definition AVLNode__avlInorderⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "root" <>,
    exception_do (let: "root" := (GoAlloc (go.PointerType AVLNode) "root") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType AVLNode] "root") =⟨go.PointerType AVLNode⟩ (Convert go.untyped_nil (go.PointerType AVLNode) UntypedNil))
    then return: (Convert go.untyped_nil (go.SliceType go.int) UntypedNil)
    else do:  #());;;
    let: "out" := (GoAlloc (go.SliceType go.int) (GoZeroVal (go.SliceType go.int) #())) in
    let: "$r0" := (let: "$a0" := (![go.SliceType go.int] "out") in
    let: "$a1" := ((MethodResolve (go.PointerType AVLNode) "avlInorder"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "root")))) #()) in
    (FuncResolve go.append [go.SliceType go.int] #()) "$a0" "$a1") in
    do:  ("out" <-[go.SliceType go.int] "$r0");;;
    let: "$r0" := (let: "$a0" := (![go.SliceType go.int] "out") in
    let: "$a1" := ((let: "$sl0" := (![go.int] (StructFieldRef AVLNode "Val"%go (![go.PointerType AVLNode] "root"))) in
    CompositeLiteral (go.SliceType go.int) (LiteralValue [KeyedElement None (ElementExpression go.int "$sl0")]))) in
    (FuncResolve go.append [go.SliceType go.int] #()) "$a0" "$a1") in
    do:  ("out" <-[go.SliceType go.int] "$r0");;;
    let: "$r0" := (let: "$a0" := (![go.SliceType go.int] "out") in
    let: "$a1" := ((MethodResolve (go.PointerType AVLNode) "avlInorder"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "root")))) #()) in
    (FuncResolve go.append [go.SliceType go.int] #()) "$a0" "$a1") in
    do:  ("out" <-[go.SliceType go.int] "$r0");;;
    return: (![go.SliceType go.int] "out")).

(* go: avl.go:86:22 *)
Definition AVLNode__AVLInsertⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "root" "v",
    exception_do (let: "root" := (GoAlloc (go.PointerType AVLNode) "root") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType AVLNode] "root") =⟨go.PointerType AVLNode⟩ (Convert go.untyped_nil (go.PointerType AVLNode) UntypedNil))
    then
      return: (GoAlloc AVLNode (let: "$v0" := (![go.int] "v") in
       CompositeLiteral AVLNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0")])))
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "v") <⟨go.int⟩ (![go.int] (StructFieldRef AVLNode "Val"%go (![go.PointerType AVLNode] "root"))))
    then
      let: "$r0" := (let: "$a0" := (![go.int] "v") in
      (MethodResolve (go.PointerType AVLNode) "AVLInsert"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "root")))) "$a0") in
      do:  ((StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "root")) <-[go.PointerType AVLNode] "$r0")
    else
      (if: Convert go.untyped_bool go.bool ((![go.int] "v") >⟨go.int⟩ (![go.int] (StructFieldRef AVLNode "Val"%go (![go.PointerType AVLNode] "root"))))
      then
        let: "$r0" := (let: "$a0" := (![go.int] "v") in
        (MethodResolve (go.PointerType AVLNode) "AVLInsert"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "root")))) "$a0") in
        do:  ((StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "root")) <-[go.PointerType AVLNode] "$r0")
      else return: (![go.PointerType AVLNode] "root")));;;
    do:  ((MethodResolve (go.PointerType AVLNode) "updateHeight"%go (![go.PointerType AVLNode] "root")) #());;;
    return: ((MethodResolve (go.PointerType AVLNode) "rebalance"%go (![go.PointerType AVLNode] "root")) #())).

(* go: avl.go:101:22 *)
Definition AVLNode__AVLDeleteⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "root" "v",
    exception_do (let: "root" := (GoAlloc (go.PointerType AVLNode) "root") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType AVLNode] "root") =⟨go.PointerType AVLNode⟩ (Convert go.untyped_nil (go.PointerType AVLNode) UntypedNil))
    then return: (Convert go.untyped_nil (go.PointerType AVLNode) UntypedNil)
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "v") <⟨go.int⟩ (![go.int] (StructFieldRef AVLNode "Val"%go (![go.PointerType AVLNode] "root"))))
    then
      let: "$r0" := (let: "$a0" := (![go.int] "v") in
      (MethodResolve (go.PointerType AVLNode) "AVLDelete"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "root")))) "$a0") in
      do:  ((StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "root")) <-[go.PointerType AVLNode] "$r0")
    else
      (if: Convert go.untyped_bool go.bool ((![go.int] "v") >⟨go.int⟩ (![go.int] (StructFieldRef AVLNode "Val"%go (![go.PointerType AVLNode] "root"))))
      then
        let: "$r0" := (let: "$a0" := (![go.int] "v") in
        (MethodResolve (go.PointerType AVLNode) "AVLDelete"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "root")))) "$a0") in
        do:  ((StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "root")) <-[go.PointerType AVLNode] "$r0")
      else
        (if: Convert go.untyped_bool go.bool ((![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "root"))) =⟨go.PointerType AVLNode⟩ (Convert go.untyped_nil (go.PointerType AVLNode) UntypedNil))
        then return: (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "root")))
        else do:  #());;;
        (if: Convert go.untyped_bool go.bool ((![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "root"))) =⟨go.PointerType AVLNode⟩ (Convert go.untyped_nil (go.PointerType AVLNode) UntypedNil))
        then return: (![go.PointerType AVLNode] (StructFieldRef AVLNode "Left"%go (![go.PointerType AVLNode] "root")))
        else do:  #());;;
        let: "successor" := (GoAlloc (go.PointerType AVLNode) (GoZeroVal (go.PointerType AVLNode) #())) in
        let: "$r0" := ((MethodResolve (go.PointerType AVLNode) "avlMin"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "root")))) #()) in
        do:  ("successor" <-[go.PointerType AVLNode] "$r0");;;
        let: "$r0" := (![go.int] (StructFieldRef AVLNode "Val"%go (![go.PointerType AVLNode] "successor"))) in
        do:  ((StructFieldRef AVLNode "Val"%go (![go.PointerType AVLNode] "root")) <-[go.int] "$r0");;;
        let: "$r0" := (let: "$a0" := (![go.int] (StructFieldRef AVLNode "Val"%go (![go.PointerType AVLNode] "successor"))) in
        (MethodResolve (go.PointerType AVLNode) "AVLDelete"%go (![go.PointerType AVLNode] (StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "root")))) "$a0") in
        do:  ((StructFieldRef AVLNode "Right"%go (![go.PointerType AVLNode] "root")) <-[go.PointerType AVLNode] "$r0")));;;
    do:  ((MethodResolve (go.PointerType AVLNode) "updateHeight"%go (![go.PointerType AVLNode] "root")) #());;;
    return: ((MethodResolve (go.PointerType AVLNode) "rebalance"%go (![go.PointerType AVLNode] "root")) #())).

(* go: bst.go:9:23 *)
Definition TreeNode__bstMinⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "root" <>,
    exception_do (let: "root" := (GoAlloc (go.PointerType TreeNode) "root") in
    (for: (λ: <>, (![go.PointerType TreeNode] (StructFieldRef TreeNode "Left"%go (![go.PointerType TreeNode] "root"))) ≠⟨go.PointerType TreeNode⟩ (Convert go.untyped_nil (go.PointerType TreeNode) UntypedNil)); (λ: <>, #()) := λ: <>,
      let: "$r0" := (![go.PointerType TreeNode] (StructFieldRef TreeNode "Left"%go (![go.PointerType TreeNode] "root"))) in
      do:  ("root" <-[go.PointerType TreeNode] "$r0"));;;
    return: (![go.PointerType TreeNode] "root")).

(* go: bst.go:16:23 *)
Definition TreeNode__bstInorderⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "root" <>,
    exception_do (let: "root" := (GoAlloc (go.PointerType TreeNode) "root") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType TreeNode] "root") =⟨go.PointerType TreeNode⟩ (Convert go.untyped_nil (go.PointerType TreeNode) UntypedNil))
    then return: (Convert go.untyped_nil (go.SliceType go.int) UntypedNil)
    else do:  #());;;
    let: "out" := (GoAlloc (go.SliceType go.int) (GoZeroVal (go.SliceType go.int) #())) in
    let: "$r0" := (let: "$a0" := (![go.SliceType go.int] "out") in
    let: "$a1" := ((MethodResolve (go.PointerType TreeNode) "bstInorder"%go (![go.PointerType TreeNode] (StructFieldRef TreeNode "Left"%go (![go.PointerType TreeNode] "root")))) #()) in
    (FuncResolve go.append [go.SliceType go.int] #()) "$a0" "$a1") in
    do:  ("out" <-[go.SliceType go.int] "$r0");;;
    let: "$r0" := (let: "$a0" := (![go.SliceType go.int] "out") in
    let: "$a1" := ((let: "$sl0" := (![go.int] (StructFieldRef TreeNode "Val"%go (![go.PointerType TreeNode] "root"))) in
    CompositeLiteral (go.SliceType go.int) (LiteralValue [KeyedElement None (ElementExpression go.int "$sl0")]))) in
    (FuncResolve go.append [go.SliceType go.int] #()) "$a0" "$a1") in
    do:  ("out" <-[go.SliceType go.int] "$r0");;;
    let: "$r0" := (let: "$a0" := (![go.SliceType go.int] "out") in
    let: "$a1" := ((MethodResolve (go.PointerType TreeNode) "bstInorder"%go (![go.PointerType TreeNode] (StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root")))) #()) in
    (FuncResolve go.append [go.SliceType go.int] #()) "$a0" "$a1") in
    do:  ("out" <-[go.SliceType go.int] "$r0");;;
    return: (![go.SliceType go.int] "out")).

(* go: bst.go:27:23 *)
Definition TreeNode__BSTContainsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "root" "v",
    exception_do (let: "root" := (GoAlloc (go.PointerType TreeNode) "root") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType TreeNode] "root") =⟨go.PointerType TreeNode⟩ (Convert go.untyped_nil (go.PointerType TreeNode) UntypedNil))
    then return: (#false)
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "v") <⟨go.int⟩ (![go.int] (StructFieldRef TreeNode "Val"%go (![go.PointerType TreeNode] "root"))))
    then
      return: (let: "$a0" := (![go.int] "v") in
       (MethodResolve (go.PointerType TreeNode) "BSTContains"%go (![go.PointerType TreeNode] (StructFieldRef TreeNode "Left"%go (![go.PointerType TreeNode] "root")))) "$a0")
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "v") >⟨go.int⟩ (![go.int] (StructFieldRef TreeNode "Val"%go (![go.PointerType TreeNode] "root"))))
    then
      return: (let: "$a0" := (![go.int] "v") in
       (MethodResolve (go.PointerType TreeNode) "BSTContains"%go (![go.PointerType TreeNode] (StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root")))) "$a0")
    else do:  #());;;
    return: (#true)).

(* go: bst.go:40:23 *)
Definition TreeNode__BSTInsertⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "root" "v",
    exception_do (let: "root" := (GoAlloc (go.PointerType TreeNode) "root") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType TreeNode] "root") =⟨go.PointerType TreeNode⟩ (Convert go.untyped_nil (go.PointerType TreeNode) UntypedNil))
    then
      return: (GoAlloc TreeNode (let: "$v0" := (![go.int] "v") in
       CompositeLiteral TreeNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0")])))
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "v") <⟨go.int⟩ (![go.int] (StructFieldRef TreeNode "Val"%go (![go.PointerType TreeNode] "root"))))
    then
      let: "$r0" := (let: "$a0" := (![go.int] "v") in
      (MethodResolve (go.PointerType TreeNode) "BSTInsert"%go (![go.PointerType TreeNode] (StructFieldRef TreeNode "Left"%go (![go.PointerType TreeNode] "root")))) "$a0") in
      do:  ((StructFieldRef TreeNode "Left"%go (![go.PointerType TreeNode] "root")) <-[go.PointerType TreeNode] "$r0")
    else
      (if: Convert go.untyped_bool go.bool ((![go.int] "v") >⟨go.int⟩ (![go.int] (StructFieldRef TreeNode "Val"%go (![go.PointerType TreeNode] "root"))))
      then
        let: "$r0" := (let: "$a0" := (![go.int] "v") in
        (MethodResolve (go.PointerType TreeNode) "BSTInsert"%go (![go.PointerType TreeNode] (StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root")))) "$a0") in
        do:  ((StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root")) <-[go.PointerType TreeNode] "$r0")
      else do:  #()));;;
    return: (![go.PointerType TreeNode] "root")).

(* go: bst.go:52:23 *)
Definition TreeNode__BSTDeleteⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "root" "v",
    exception_do (let: "root" := (GoAlloc (go.PointerType TreeNode) "root") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType TreeNode] "root") =⟨go.PointerType TreeNode⟩ (Convert go.untyped_nil (go.PointerType TreeNode) UntypedNil))
    then return: (Convert go.untyped_nil (go.PointerType TreeNode) UntypedNil)
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "v") <⟨go.int⟩ (![go.int] (StructFieldRef TreeNode "Val"%go (![go.PointerType TreeNode] "root"))))
    then
      let: "$r0" := (let: "$a0" := (![go.int] "v") in
      (MethodResolve (go.PointerType TreeNode) "BSTDelete"%go (![go.PointerType TreeNode] (StructFieldRef TreeNode "Left"%go (![go.PointerType TreeNode] "root")))) "$a0") in
      do:  ((StructFieldRef TreeNode "Left"%go (![go.PointerType TreeNode] "root")) <-[go.PointerType TreeNode] "$r0")
    else
      (if: Convert go.untyped_bool go.bool ((![go.int] "v") >⟨go.int⟩ (![go.int] (StructFieldRef TreeNode "Val"%go (![go.PointerType TreeNode] "root"))))
      then
        let: "$r0" := (let: "$a0" := (![go.int] "v") in
        (MethodResolve (go.PointerType TreeNode) "BSTDelete"%go (![go.PointerType TreeNode] (StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root")))) "$a0") in
        do:  ((StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root")) <-[go.PointerType TreeNode] "$r0")
      else
        (if: Convert go.untyped_bool go.bool ((![go.PointerType TreeNode] (StructFieldRef TreeNode "Left"%go (![go.PointerType TreeNode] "root"))) =⟨go.PointerType TreeNode⟩ (Convert go.untyped_nil (go.PointerType TreeNode) UntypedNil))
        then return: (![go.PointerType TreeNode] (StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root")))
        else do:  #());;;
        (if: Convert go.untyped_bool go.bool ((![go.PointerType TreeNode] (StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root"))) =⟨go.PointerType TreeNode⟩ (Convert go.untyped_nil (go.PointerType TreeNode) UntypedNil))
        then return: (![go.PointerType TreeNode] (StructFieldRef TreeNode "Left"%go (![go.PointerType TreeNode] "root")))
        else do:  #());;;
        let: "successor" := (GoAlloc (go.PointerType TreeNode) (GoZeroVal (go.PointerType TreeNode) #())) in
        let: "$r0" := ((MethodResolve (go.PointerType TreeNode) "bstMin"%go (![go.PointerType TreeNode] (StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root")))) #()) in
        do:  ("successor" <-[go.PointerType TreeNode] "$r0");;;
        let: "$r0" := (![go.int] (StructFieldRef TreeNode "Val"%go (![go.PointerType TreeNode] "successor"))) in
        do:  ((StructFieldRef TreeNode "Val"%go (![go.PointerType TreeNode] "root")) <-[go.int] "$r0");;;
        let: "$r0" := (let: "$a0" := (![go.int] (StructFieldRef TreeNode "Val"%go (![go.PointerType TreeNode] "successor"))) in
        (MethodResolve (go.PointerType TreeNode) "BSTDelete"%go (![go.PointerType TreeNode] (StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root")))) "$a0") in
        do:  ((StructFieldRef TreeNode "Right"%go (![go.PointerType TreeNode] "root")) <-[go.PointerType TreeNode] "$r0")));;;
    return: (![go.PointerType TreeNode] "root")).

(* go: helpers.go:5:23 *)
Definition ListNode__toSliceⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" <>,
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "out" := (GoAlloc (go.SliceType go.int) (GoZeroVal (go.SliceType go.int) #())) in
    (let: "cur" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (![go.PointerType ListNode] "head") in
    do:  ("cur" <-[go.PointerType ListNode] "$r0");;;
    (for: (λ: <>, (![go.PointerType ListNode] "cur") ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)); (λ: <>, let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) in
    do:  ("cur" <-[go.PointerType ListNode] "$r0")) := λ: <>,
      let: "$r0" := (let: "$a0" := (![go.SliceType go.int] "out") in
      let: "$a1" := ((let: "$sl0" := (![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "cur"))) in
      CompositeLiteral (go.SliceType go.int) (LiteralValue [KeyedElement None (ElementExpression go.int "$sl0")]))) in
      (FuncResolve go.append [go.SliceType go.int] #()) "$a0" "$a1") in
      do:  ("out" <-[go.SliceType go.int] "$r0")));;;
    return: (![go.SliceType go.int] "out")).

(* go: helpers.go:13:6 *)
Definition fromSliceⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "vals",
    exception_do (let: "vals" := (GoAlloc (go.SliceType go.int) "vals") in
    let: "head" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    (let: "i" := (GoAlloc go.int (GoZeroVal go.int #())) in
    let: "$r0" := ((let: "$a0" := (![go.SliceType go.int] "vals") in
    (FuncResolve go.len [go.SliceType go.int] #()) "$a0") -⟨go.int⟩ #(W64 1)) in
    do:  ("i" <-[go.int] "$r0");;;
    (for: (λ: <>, (![go.int] "i") ≥⟨go.int⟩ #(W64 0)); (λ: <>, do:  ("i" <-[go.int] ((![go.int] "i") -⟨go.int⟩ #(W64 1)))) := λ: <>,
      let: "$r0" := (GoAlloc ListNode (let: "$v0" := (![go.int] (IndexRef (go.SliceType go.int) (![go.SliceType go.int] "vals", ![go.int] "i"))) in
      let: "$v1" := (![go.PointerType ListNode] "head") in
      CompositeLiteral ListNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0"); KeyedElement (Some (KeyField "Next"%go)) (ElementExpression (go.PointerType ListNode) "$v1")]))) in
      do:  ("head" <-[go.PointerType ListNode] "$r0")));;;
    return: (![go.PointerType ListNode] "head")).

(* go: linkedlist.go:8:23 *)
Definition ListNode__Containsⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    (let: "cur" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (![go.PointerType ListNode] "head") in
    do:  ("cur" <-[go.PointerType ListNode] "$r0");;;
    (for: (λ: <>, (![go.PointerType ListNode] "cur") ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)); (λ: <>, let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) in
    do:  ("cur" <-[go.PointerType ListNode] "$r0")) := λ: <>,
      (if: Convert go.untyped_bool go.bool ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "cur"))) =⟨go.int⟩ (![go.int] "v"))
      then return: (#true)
      else do:  #())));;;
    return: (#false)).

(* go: linkedlist.go:17:23 *)
Definition ListNode__ContainsRecursiveⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "head") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then return: (#false)
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head"))) =⟨go.int⟩ (![go.int] "v"))
    then return: (#true)
    else do:  #());;;
    return: (let: "$a0" := (![go.int] "v") in
     (MethodResolve (go.PointerType ListNode) "ContainsRecursive"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")))) "$a0")).

(* go: linkedlist.go:27:23 *)
Definition ListNode__InsertFrontⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    return: (GoAlloc ListNode (let: "$v0" := (![go.int] "v") in
     let: "$v1" := (![go.PointerType ListNode] "head") in
     CompositeLiteral ListNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0"); KeyedElement (Some (KeyField "Next"%go)) (ElementExpression (go.PointerType ListNode) "$v1")])))).

(* go: linkedlist.go:31:23 *)
Definition ListNode__InsertBackⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    let: "newNode" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (GoAlloc ListNode (let: "$v0" := (![go.int] "v") in
    CompositeLiteral ListNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0")]))) in
    do:  ("newNode" <-[go.PointerType ListNode] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "head") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then return: (![go.PointerType ListNode] "newNode")
    else do:  #());;;
    let: "cur" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (![go.PointerType ListNode] "head") in
    do:  ("cur" <-[go.PointerType ListNode] "$r0");;;
    (for: (λ: <>, (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)); (λ: <>, #()) := λ: <>,
      let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) in
      do:  ("cur" <-[go.PointerType ListNode] "$r0"));;;
    let: "$r0" := (![go.PointerType ListNode] "newNode") in
    do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur")) <-[go.PointerType ListNode] "$r0");;;
    return: (![go.PointerType ListNode] "head")).

(* go: linkedlist.go:44:23 *)
Definition ListNode__InsertBackRecursiveⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "head") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then
      return: (GoAlloc ListNode (let: "$v0" := (![go.int] "v") in
       CompositeLiteral ListNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0")])))
    else do:  #());;;
    let: "$r0" := (let: "$a0" := (![go.int] "v") in
    (MethodResolve (go.PointerType ListNode) "InsertBackRecursive"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")))) "$a0") in
    do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")) <-[go.PointerType ListNode] "$r0");;;
    return: (![go.PointerType ListNode] "head")).

(* go: linkedlist.go:52:23 *)
Definition ListNode__DeleteAllⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    (for: (λ: <>, ((![go.PointerType ListNode] "head") ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)) && ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head"))) =⟨go.int⟩ (![go.int] "v"))); (λ: <>, #()) := λ: <>,
      let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head"))) in
      do:  ("head" <-[go.PointerType ListNode] "$r0"));;;
    let: "cur" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (![go.PointerType ListNode] "head") in
    do:  ("cur" <-[go.PointerType ListNode] "$r0");;;
    (for: (λ: <>, ((![go.PointerType ListNode] "cur") ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)) && ((![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))); (λ: <>, #()) := λ: <>,
      (if: Convert go.untyped_bool go.bool ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))))) =⟨go.int⟩ (![go.int] "v"))
      then
        let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))))) in
        do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur")) <-[go.PointerType ListNode] "$r0")
      else
        let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) in
        do:  ("cur" <-[go.PointerType ListNode] "$r0")));;;
    return: (![go.PointerType ListNode] "head")).

(* go: linkedlist.go:67:23 *)
Definition ListNode__DeleteAllRecursiveⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "head") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then return: (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)
    else do:  #());;;
    let: "$r0" := (let: "$a0" := (![go.int] "v") in
    (MethodResolve (go.PointerType ListNode) "DeleteAllRecursive"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")))) "$a0") in
    do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")) <-[go.PointerType ListNode] "$r0");;;
    (if: Convert go.untyped_bool go.bool ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head"))) =⟨go.int⟩ (![go.int] "v"))
    then return: (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")))
    else do:  #());;;
    return: (![go.PointerType ListNode] "head")).

(* go: linkedlist.go:78:23 *)
Definition ListNode__CopyListⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" <>,
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "head") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then return: (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)
    else do:  #());;;
    let: "newHead" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (GoAlloc ListNode (let: "$v0" := (![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head"))) in
    CompositeLiteral ListNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0")]))) in
    do:  ("newHead" <-[go.PointerType ListNode] "$r0");;;
    let: "cur" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head"))) in
    do:  ("cur" <-[go.PointerType ListNode] "$r0");;;
    let: "tail" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (![go.PointerType ListNode] "newHead") in
    do:  ("tail" <-[go.PointerType ListNode] "$r0");;;
    (for: (λ: <>, (![go.PointerType ListNode] "cur") ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)); (λ: <>, #()) := λ: <>,
      let: "$r0" := (GoAlloc ListNode (let: "$v0" := (![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "cur"))) in
      CompositeLiteral ListNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0")]))) in
      do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "tail")) <-[go.PointerType ListNode] "$r0");;;
      let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "tail"))) in
      do:  ("tail" <-[go.PointerType ListNode] "$r0");;;
      let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) in
      do:  ("cur" <-[go.PointerType ListNode] "$r0"));;;
    return: (![go.PointerType ListNode] "newHead")).

(* go: linkedlist.go:93:23 *)
Definition ListNode__CopyListRecursiveⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" <>,
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "head") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then return: (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)
    else do:  #());;;
    return: (GoAlloc ListNode (let: "$v0" := (![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head"))) in
     let: "$v1" := ((MethodResolve (go.PointerType ListNode) "CopyListRecursive"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")))) #()) in
     CompositeLiteral ListNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0"); KeyedElement (Some (KeyField "Next"%go)) (ElementExpression (go.PointerType ListNode) "$v1")])))).

(* go: sortedlist.go:6:23 *)
Definition ListNode__SortedInsertⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool (((![go.PointerType ListNode] "head") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)) || ((![go.int] "v") <⟨go.int⟩ (![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head")))))
    then
      return: (GoAlloc ListNode (let: "$v0" := (![go.int] "v") in
       let: "$v1" := (![go.PointerType ListNode] "head") in
       CompositeLiteral ListNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0"); KeyedElement (Some (KeyField "Next"%go)) (ElementExpression (go.PointerType ListNode) "$v1")])))
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "v") =⟨go.int⟩ (![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head"))))
    then return: (![go.PointerType ListNode] "head")
    else do:  #());;;
    let: "cur" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (![go.PointerType ListNode] "head") in
    do:  ("cur" <-[go.PointerType ListNode] "$r0");;;
    (for: (λ: <>, ((![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)) && ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))))) <⟨go.int⟩ (![go.int] "v"))); (λ: <>, #()) := λ: <>,
      let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) in
      do:  ("cur" <-[go.PointerType ListNode] "$r0"));;;
    (if: Convert go.untyped_bool go.bool (((![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)) && ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))))) =⟨go.int⟩ (![go.int] "v")))
    then return: (![go.PointerType ListNode] "head")
    else do:  #());;;
    let: "$r0" := (GoAlloc ListNode (let: "$v0" := (![go.int] "v") in
    let: "$v1" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) in
    CompositeLiteral ListNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0"); KeyedElement (Some (KeyField "Next"%go)) (ElementExpression (go.PointerType ListNode) "$v1")]))) in
    do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur")) <-[go.PointerType ListNode] "$r0");;;
    return: (![go.PointerType ListNode] "head")).

(* go: sortedlist.go:24:23 *)
Definition ListNode__SortedInsertRecursiveⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool (((![go.PointerType ListNode] "head") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)) || ((![go.int] "v") <⟨go.int⟩ (![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head")))))
    then
      return: (GoAlloc ListNode (let: "$v0" := (![go.int] "v") in
       let: "$v1" := (![go.PointerType ListNode] "head") in
       CompositeLiteral ListNode (LiteralValue [KeyedElement (Some (KeyField "Val"%go)) (ElementExpression go.int "$v0"); KeyedElement (Some (KeyField "Next"%go)) (ElementExpression (go.PointerType ListNode) "$v1")])))
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] "v") =⟨go.int⟩ (![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head"))))
    then return: (![go.PointerType ListNode] "head")
    else do:  #());;;
    let: "$r0" := (let: "$a0" := (![go.int] "v") in
    (MethodResolve (go.PointerType ListNode) "SortedInsertRecursive"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")))) "$a0") in
    do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")) <-[go.PointerType ListNode] "$r0");;;
    return: (![go.PointerType ListNode] "head")).

(* go: sortedlist.go:35:23 *)
Definition ListNode__SortedDeleteⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "head") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then return: (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head"))) =⟨go.int⟩ (![go.int] "v"))
    then return: (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")))
    else do:  #());;;
    let: "cur" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (![go.PointerType ListNode] "head") in
    do:  ("cur" <-[go.PointerType ListNode] "$r0");;;
    (for: (λ: <>, ((![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)) && ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))))) ≠⟨go.int⟩ (![go.int] "v"))); (λ: <>, #()) := λ: <>,
      let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) in
      do:  ("cur" <-[go.PointerType ListNode] "$r0"));;;
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))) ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then
      let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur"))))) in
      do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "cur")) <-[go.PointerType ListNode] "$r0")
    else do:  #());;;
    return: (![go.PointerType ListNode] "head")).

(* go: sortedlist.go:52:23 *)
Definition ListNode__SortedDeleteRecursiveⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "head" "v",
    exception_do (let: "head" := (GoAlloc (go.PointerType ListNode) "head") in
    let: "v" := (GoAlloc go.int "v") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "head") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then return: (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "head"))) =⟨go.int⟩ (![go.int] "v"))
    then return: (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")))
    else do:  #());;;
    let: "$r0" := (let: "$a0" := (![go.int] "v") in
    (MethodResolve (go.PointerType ListNode) "SortedDeleteRecursive"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")))) "$a0") in
    do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "head")) <-[go.PointerType ListNode] "$r0");;;
    return: (![go.PointerType ListNode] "head")).

(* go: sortedlist.go:63:20 *)
Definition ListNode__Mergeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "a" "b",
    exception_do (let: "a" := (GoAlloc (go.PointerType ListNode) "a") in
    let: "b" := (GoAlloc (go.PointerType ListNode) "b") in
    let: "dummy" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (GoAlloc ListNode (CompositeLiteral ListNode (LiteralValue []))) in
    do:  ("dummy" <-[go.PointerType ListNode] "$r0");;;
    let: "tail" := (GoAlloc (go.PointerType ListNode) (GoZeroVal (go.PointerType ListNode) #())) in
    let: "$r0" := (![go.PointerType ListNode] "dummy") in
    do:  ("tail" <-[go.PointerType ListNode] "$r0");;;
    (for: (λ: <>, ((![go.PointerType ListNode] "a") ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil)) && ((![go.PointerType ListNode] "b") ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))); (λ: <>, #()) := λ: <>,
      (if: Convert go.untyped_bool go.bool ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "a"))) ≤⟨go.int⟩ (![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "b"))))
      then
        let: "$r0" := (![go.PointerType ListNode] "a") in
        do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "tail")) <-[go.PointerType ListNode] "$r0");;;
        let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "a"))) in
        do:  ("a" <-[go.PointerType ListNode] "$r0")
      else
        let: "$r0" := (![go.PointerType ListNode] "b") in
        do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "tail")) <-[go.PointerType ListNode] "$r0");;;
        let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "b"))) in
        do:  ("b" <-[go.PointerType ListNode] "$r0"));;;
      let: "$r0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "tail"))) in
      do:  ("tail" <-[go.PointerType ListNode] "$r0"));;;
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "a") ≠⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then
      let: "$r0" := (![go.PointerType ListNode] "a") in
      do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "tail")) <-[go.PointerType ListNode] "$r0")
    else
      let: "$r0" := (![go.PointerType ListNode] "b") in
      do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "tail")) <-[go.PointerType ListNode] "$r0"));;;
    return: (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "dummy")))).

(* go: sortedlist.go:84:20 *)
Definition ListNode__MergeRecursiveⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "a" "b",
    exception_do (let: "a" := (GoAlloc (go.PointerType ListNode) "a") in
    let: "b" := (GoAlloc (go.PointerType ListNode) "b") in
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "a") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then return: (![go.PointerType ListNode] "b")
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.PointerType ListNode] "b") =⟨go.PointerType ListNode⟩ (Convert go.untyped_nil (go.PointerType ListNode) UntypedNil))
    then return: (![go.PointerType ListNode] "a")
    else do:  #());;;
    (if: Convert go.untyped_bool go.bool ((![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "a"))) ≤⟨go.int⟩ (![go.int] (StructFieldRef ListNode "Val"%go (![go.PointerType ListNode] "b"))))
    then
      let: "$r0" := (let: "$a0" := (![go.PointerType ListNode] "b") in
      (MethodResolve (go.PointerType ListNode) "MergeRecursive"%go (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "a")))) "$a0") in
      do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "a")) <-[go.PointerType ListNode] "$r0");;;
      return: (![go.PointerType ListNode] "a")
    else do:  #());;;
    let: "$r0" := (let: "$a0" := (![go.PointerType ListNode] (StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "b"))) in
    (MethodResolve (go.PointerType ListNode) "MergeRecursive"%go (![go.PointerType ListNode] "a")) "$a0") in
    do:  ((StructFieldRef ListNode "Next"%go (![go.PointerType ListNode] "b")) <-[go.PointerType ListNode] "$r0");;;
    return: (![go.PointerType ListNode] "b")).

#[global] Instance info' : PkgInfo pkg_id.heapexamples :=
{|
  pkg_imported_pkgs := []
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.heapexamples (λ: <>,
      exception_do (do:  #())
      ).

Module AVLNode.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  Val' : w64;
  Left' : loc;
  Right' : loc;
  Height' : w64;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.

End AVLNode.

Definition AVLNode'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "Val"%go go.int);
  (go.FieldDecl "Left"%go (go.PointerType AVLNode));
  (go.FieldDecl "Right"%go (go.PointerType AVLNode));
  (go.FieldDecl "Height"%go go.int)
].
Program Definition AVLNode'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (AVLNode'fds_unsealed).
Global Instance equals_unfold_AVLNode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : AVLNode'fds =→ AVLNode'fds_unsealed.
Proof. rewrite /AVLNode'fds seal_eq //. Qed.

Definition AVLNodeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (AVLNode'fds).

Class AVLNode_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] AVLNode_type_repr  :: go.TypeReprUnderlying AVLNodeⁱᵐᵖˡ AVLNode.t;
  #[global] AVLNode_underlying :: (AVLNode) <u (AVLNodeⁱᵐᵖˡ);
  #[global] AVLNode_get_Val (x : AVLNode.t) :: ⟦StructFieldGet (AVLNodeⁱᵐᵖˡ) "Val", #x⟧ ⤳[under] #x.(AVLNode.Val');
  #[global] AVLNode_set_Val (x : AVLNode.t) y :: ⟦StructFieldSet (AVLNodeⁱᵐᵖˡ) "Val", (#x, #y)⟧ ⤳[under] #(x <|AVLNode.Val' := y|>);
  #[global] AVLNode_get_Left (x : AVLNode.t) :: ⟦StructFieldGet (AVLNodeⁱᵐᵖˡ) "Left", #x⟧ ⤳[under] #x.(AVLNode.Left');
  #[global] AVLNode_set_Left (x : AVLNode.t) y :: ⟦StructFieldSet (AVLNodeⁱᵐᵖˡ) "Left", (#x, #y)⟧ ⤳[under] #(x <|AVLNode.Left' := y|>);
  #[global] AVLNode_get_Right (x : AVLNode.t) :: ⟦StructFieldGet (AVLNodeⁱᵐᵖˡ) "Right", #x⟧ ⤳[under] #x.(AVLNode.Right');
  #[global] AVLNode_set_Right (x : AVLNode.t) y :: ⟦StructFieldSet (AVLNodeⁱᵐᵖˡ) "Right", (#x, #y)⟧ ⤳[under] #(x <|AVLNode.Right' := y|>);
  #[global] AVLNode_get_Height (x : AVLNode.t) :: ⟦StructFieldGet (AVLNodeⁱᵐᵖˡ) "Height", #x⟧ ⤳[under] #x.(AVLNode.Height');
  #[global] AVLNode_set_Height (x : AVLNode.t) y :: ⟦StructFieldSet (AVLNodeⁱᵐᵖˡ) "Height", (#x, #y)⟧ ⤳[under] #(x <|AVLNode.Height' := y|>);
  #[global] AVLNode'ptr_AVLDelete_unfold :: MethodUnfold (go.PointerType (AVLNode)) "AVLDelete" (AVLNode__AVLDeleteⁱᵐᵖˡ);
  #[global] AVLNode'ptr_AVLInsert_unfold :: MethodUnfold (go.PointerType (AVLNode)) "AVLInsert" (AVLNode__AVLInsertⁱᵐᵖˡ);
  #[global] AVLNode'ptr_avlInorder_unfold :: MethodUnfold (go.PointerType (AVLNode)) "avlInorder" (AVLNode__avlInorderⁱᵐᵖˡ);
  #[global] AVLNode'ptr_avlMin_unfold :: MethodUnfold (go.PointerType (AVLNode)) "avlMin" (AVLNode__avlMinⁱᵐᵖˡ);
  #[global] AVLNode'ptr_balanceFactor_unfold :: MethodUnfold (go.PointerType (AVLNode)) "balanceFactor" (AVLNode__balanceFactorⁱᵐᵖˡ);
  #[global] AVLNode'ptr_height_unfold :: MethodUnfold (go.PointerType (AVLNode)) "height" (AVLNode__heightⁱᵐᵖˡ);
  #[global] AVLNode'ptr_rebalance_unfold :: MethodUnfold (go.PointerType (AVLNode)) "rebalance" (AVLNode__rebalanceⁱᵐᵖˡ);
  #[global] AVLNode'ptr_rotateLeft_unfold :: MethodUnfold (go.PointerType (AVLNode)) "rotateLeft" (AVLNode__rotateLeftⁱᵐᵖˡ);
  #[global] AVLNode'ptr_rotateRight_unfold :: MethodUnfold (go.PointerType (AVLNode)) "rotateRight" (AVLNode__rotateRightⁱᵐᵖˡ);
  #[global] AVLNode'ptr_updateHeight_unfold :: MethodUnfold (go.PointerType (AVLNode)) "updateHeight" (AVLNode__updateHeightⁱᵐᵖˡ);
}.

Module TreeNode.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  Val' : w64;
  Left' : loc;
  Right' : loc;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.

End TreeNode.

Definition TreeNode'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "Val"%go go.int);
  (go.FieldDecl "Left"%go (go.PointerType TreeNode));
  (go.FieldDecl "Right"%go (go.PointerType TreeNode))
].
Program Definition TreeNode'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (TreeNode'fds_unsealed).
Global Instance equals_unfold_TreeNode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : TreeNode'fds =→ TreeNode'fds_unsealed.
Proof. rewrite /TreeNode'fds seal_eq //. Qed.

Definition TreeNodeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (TreeNode'fds).

Class TreeNode_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] TreeNode_type_repr  :: go.TypeReprUnderlying TreeNodeⁱᵐᵖˡ TreeNode.t;
  #[global] TreeNode_underlying :: (TreeNode) <u (TreeNodeⁱᵐᵖˡ);
  #[global] TreeNode_get_Val (x : TreeNode.t) :: ⟦StructFieldGet (TreeNodeⁱᵐᵖˡ) "Val", #x⟧ ⤳[under] #x.(TreeNode.Val');
  #[global] TreeNode_set_Val (x : TreeNode.t) y :: ⟦StructFieldSet (TreeNodeⁱᵐᵖˡ) "Val", (#x, #y)⟧ ⤳[under] #(x <|TreeNode.Val' := y|>);
  #[global] TreeNode_get_Left (x : TreeNode.t) :: ⟦StructFieldGet (TreeNodeⁱᵐᵖˡ) "Left", #x⟧ ⤳[under] #x.(TreeNode.Left');
  #[global] TreeNode_set_Left (x : TreeNode.t) y :: ⟦StructFieldSet (TreeNodeⁱᵐᵖˡ) "Left", (#x, #y)⟧ ⤳[under] #(x <|TreeNode.Left' := y|>);
  #[global] TreeNode_get_Right (x : TreeNode.t) :: ⟦StructFieldGet (TreeNodeⁱᵐᵖˡ) "Right", #x⟧ ⤳[under] #x.(TreeNode.Right');
  #[global] TreeNode_set_Right (x : TreeNode.t) y :: ⟦StructFieldSet (TreeNodeⁱᵐᵖˡ) "Right", (#x, #y)⟧ ⤳[under] #(x <|TreeNode.Right' := y|>);
  #[global] TreeNode'ptr_BSTContains_unfold :: MethodUnfold (go.PointerType (TreeNode)) "BSTContains" (TreeNode__BSTContainsⁱᵐᵖˡ);
  #[global] TreeNode'ptr_BSTDelete_unfold :: MethodUnfold (go.PointerType (TreeNode)) "BSTDelete" (TreeNode__BSTDeleteⁱᵐᵖˡ);
  #[global] TreeNode'ptr_BSTInsert_unfold :: MethodUnfold (go.PointerType (TreeNode)) "BSTInsert" (TreeNode__BSTInsertⁱᵐᵖˡ);
  #[global] TreeNode'ptr_bstInorder_unfold :: MethodUnfold (go.PointerType (TreeNode)) "bstInorder" (TreeNode__bstInorderⁱᵐᵖˡ);
  #[global] TreeNode'ptr_bstMin_unfold :: MethodUnfold (go.PointerType (TreeNode)) "bstMin" (TreeNode__bstMinⁱᵐᵖˡ);
}.

Module ListNode.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  Val' : w64;
  Next' : loc;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _) (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.

End ListNode.

Definition ListNode'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "Val"%go go.int);
  (go.FieldDecl "Next"%go (go.PointerType ListNode))
].
Program Definition ListNode'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (ListNode'fds_unsealed).
Global Instance equals_unfold_ListNode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : ListNode'fds =→ ListNode'fds_unsealed.
Proof. rewrite /ListNode'fds seal_eq //. Qed.

Definition ListNodeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (ListNode'fds).

Class ListNode_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] ListNode_type_repr  :: go.TypeReprUnderlying ListNodeⁱᵐᵖˡ ListNode.t;
  #[global] ListNode_underlying :: (ListNode) <u (ListNodeⁱᵐᵖˡ);
  #[global] ListNode_get_Val (x : ListNode.t) :: ⟦StructFieldGet (ListNodeⁱᵐᵖˡ) "Val", #x⟧ ⤳[under] #x.(ListNode.Val');
  #[global] ListNode_set_Val (x : ListNode.t) y :: ⟦StructFieldSet (ListNodeⁱᵐᵖˡ) "Val", (#x, #y)⟧ ⤳[under] #(x <|ListNode.Val' := y|>);
  #[global] ListNode_get_Next (x : ListNode.t) :: ⟦StructFieldGet (ListNodeⁱᵐᵖˡ) "Next", #x⟧ ⤳[under] #x.(ListNode.Next');
  #[global] ListNode_set_Next (x : ListNode.t) y :: ⟦StructFieldSet (ListNodeⁱᵐᵖˡ) "Next", (#x, #y)⟧ ⤳[under] #(x <|ListNode.Next' := y|>);
  #[global] ListNode'ptr_Contains_unfold :: MethodUnfold (go.PointerType (ListNode)) "Contains" (ListNode__Containsⁱᵐᵖˡ);
  #[global] ListNode'ptr_ContainsRecursive_unfold :: MethodUnfold (go.PointerType (ListNode)) "ContainsRecursive" (ListNode__ContainsRecursiveⁱᵐᵖˡ);
  #[global] ListNode'ptr_CopyList_unfold :: MethodUnfold (go.PointerType (ListNode)) "CopyList" (ListNode__CopyListⁱᵐᵖˡ);
  #[global] ListNode'ptr_CopyListRecursive_unfold :: MethodUnfold (go.PointerType (ListNode)) "CopyListRecursive" (ListNode__CopyListRecursiveⁱᵐᵖˡ);
  #[global] ListNode'ptr_DeleteAll_unfold :: MethodUnfold (go.PointerType (ListNode)) "DeleteAll" (ListNode__DeleteAllⁱᵐᵖˡ);
  #[global] ListNode'ptr_DeleteAllRecursive_unfold :: MethodUnfold (go.PointerType (ListNode)) "DeleteAllRecursive" (ListNode__DeleteAllRecursiveⁱᵐᵖˡ);
  #[global] ListNode'ptr_InsertBack_unfold :: MethodUnfold (go.PointerType (ListNode)) "InsertBack" (ListNode__InsertBackⁱᵐᵖˡ);
  #[global] ListNode'ptr_InsertBackRecursive_unfold :: MethodUnfold (go.PointerType (ListNode)) "InsertBackRecursive" (ListNode__InsertBackRecursiveⁱᵐᵖˡ);
  #[global] ListNode'ptr_InsertFront_unfold :: MethodUnfold (go.PointerType (ListNode)) "InsertFront" (ListNode__InsertFrontⁱᵐᵖˡ);
  #[global] ListNode'ptr_Merge_unfold :: MethodUnfold (go.PointerType (ListNode)) "Merge" (ListNode__Mergeⁱᵐᵖˡ);
  #[global] ListNode'ptr_MergeRecursive_unfold :: MethodUnfold (go.PointerType (ListNode)) "MergeRecursive" (ListNode__MergeRecursiveⁱᵐᵖˡ);
  #[global] ListNode'ptr_SortedDelete_unfold :: MethodUnfold (go.PointerType (ListNode)) "SortedDelete" (ListNode__SortedDeleteⁱᵐᵖˡ);
  #[global] ListNode'ptr_SortedDeleteRecursive_unfold :: MethodUnfold (go.PointerType (ListNode)) "SortedDeleteRecursive" (ListNode__SortedDeleteRecursiveⁱᵐᵖˡ);
  #[global] ListNode'ptr_SortedInsert_unfold :: MethodUnfold (go.PointerType (ListNode)) "SortedInsert" (ListNode__SortedInsertⁱᵐᵖˡ);
  #[global] ListNode'ptr_SortedInsertRecursive_unfold :: MethodUnfold (go.PointerType (ListNode)) "SortedInsertRecursive" (ListNode__SortedInsertRecursiveⁱᵐᵖˡ);
  #[global] ListNode'ptr_toSlice_unfold :: MethodUnfold (go.PointerType (ListNode)) "toSlice" (ListNode__toSliceⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] AVLNode_instance :: AVLNode_Assumptions;
  #[global] TreeNode_instance :: TreeNode_Assumptions;
  #[global] ListNode_instance :: ListNode_Assumptions;
  #[global] fromSlice_unfold :: FuncUnfold fromSlice [] (fromSliceⁱᵐᵖˡ);
}.
End heapexamples.
