(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.github_com.codyjrivera.heapexamples.

Set Default Proof Using "Type".

Module heapexamples.
Module AVLNode.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : heapexamples.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance AVLNode_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (heapexamples.AVLNode.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Val" ∷ l.[(heapexamples.AVLNode.t), "Val"] ↦{dq} v.(heapexamples.AVLNode.Val') ∗
      "Left" ∷ l.[(heapexamples.AVLNode.t), "Left"] ↦{dq} v.(heapexamples.AVLNode.Left') ∗
      "Right" ∷ l.[(heapexamples.AVLNode.t), "Right"] ↦{dq} v.(heapexamples.AVLNode.Right') ∗
      "Height" ∷ l.[(heapexamples.AVLNode.t), "Height"] ↦{dq} v.(heapexamples.AVLNode.Height') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance AVLNode_into_val_typed
   :
  IntoValTypedUnderlying (heapexamples.AVLNode.t) (heapexamples.AVLNodeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance AVLNode_access_load_Val l (v : (heapexamples.AVLNode.t)) dq :
  AccessStrict
    (l.[(heapexamples.AVLNode.t), "Val"] ↦{dq} (v.(heapexamples.AVLNode.Val')))
    (l.[(heapexamples.AVLNode.t), "Val"] ↦{dq} (v.(heapexamples.AVLNode.Val')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance AVLNode_access_store_Val l (v : (heapexamples.AVLNode.t)) Val' :
  AccessStrict
    (l.[(heapexamples.AVLNode.t), "Val"] ↦ (v.(heapexamples.AVLNode.Val')))
    (l.[(heapexamples.AVLNode.t), "Val"] ↦ Val')
    (l ↦ v) (l ↦ (v <|(heapexamples.AVLNode.Val') := Val'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance AVLNode_access_load_Left l (v : (heapexamples.AVLNode.t)) dq :
  AccessStrict
    (l.[(heapexamples.AVLNode.t), "Left"] ↦{dq} (v.(heapexamples.AVLNode.Left')))
    (l.[(heapexamples.AVLNode.t), "Left"] ↦{dq} (v.(heapexamples.AVLNode.Left')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance AVLNode_access_store_Left l (v : (heapexamples.AVLNode.t)) Left' :
  AccessStrict
    (l.[(heapexamples.AVLNode.t), "Left"] ↦ (v.(heapexamples.AVLNode.Left')))
    (l.[(heapexamples.AVLNode.t), "Left"] ↦ Left')
    (l ↦ v) (l ↦ (v <|(heapexamples.AVLNode.Left') := Left'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance AVLNode_access_load_Right l (v : (heapexamples.AVLNode.t)) dq :
  AccessStrict
    (l.[(heapexamples.AVLNode.t), "Right"] ↦{dq} (v.(heapexamples.AVLNode.Right')))
    (l.[(heapexamples.AVLNode.t), "Right"] ↦{dq} (v.(heapexamples.AVLNode.Right')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance AVLNode_access_store_Right l (v : (heapexamples.AVLNode.t)) Right' :
  AccessStrict
    (l.[(heapexamples.AVLNode.t), "Right"] ↦ (v.(heapexamples.AVLNode.Right')))
    (l.[(heapexamples.AVLNode.t), "Right"] ↦ Right')
    (l ↦ v) (l ↦ (v <|(heapexamples.AVLNode.Right') := Right'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance AVLNode_access_load_Height l (v : (heapexamples.AVLNode.t)) dq :
  AccessStrict
    (l.[(heapexamples.AVLNode.t), "Height"] ↦{dq} (v.(heapexamples.AVLNode.Height')))
    (l.[(heapexamples.AVLNode.t), "Height"] ↦{dq} (v.(heapexamples.AVLNode.Height')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance AVLNode_access_store_Height l (v : (heapexamples.AVLNode.t)) Height' :
  AccessStrict
    (l.[(heapexamples.AVLNode.t), "Height"] ↦ (v.(heapexamples.AVLNode.Height')))
    (l.[(heapexamples.AVLNode.t), "Height"] ↦ Height')
    (l ↦ v) (l ↦ (v <|(heapexamples.AVLNode.Height') := Height'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End AVLNode.

Module TreeNode.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : heapexamples.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance TreeNode_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (heapexamples.TreeNode.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Val" ∷ l.[(heapexamples.TreeNode.t), "Val"] ↦{dq} v.(heapexamples.TreeNode.Val') ∗
      "Left" ∷ l.[(heapexamples.TreeNode.t), "Left"] ↦{dq} v.(heapexamples.TreeNode.Left') ∗
      "Right" ∷ l.[(heapexamples.TreeNode.t), "Right"] ↦{dq} v.(heapexamples.TreeNode.Right') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance TreeNode_into_val_typed
   :
  IntoValTypedUnderlying (heapexamples.TreeNode.t) (heapexamples.TreeNodeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance TreeNode_access_load_Val l (v : (heapexamples.TreeNode.t)) dq :
  AccessStrict
    (l.[(heapexamples.TreeNode.t), "Val"] ↦{dq} (v.(heapexamples.TreeNode.Val')))
    (l.[(heapexamples.TreeNode.t), "Val"] ↦{dq} (v.(heapexamples.TreeNode.Val')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance TreeNode_access_store_Val l (v : (heapexamples.TreeNode.t)) Val' :
  AccessStrict
    (l.[(heapexamples.TreeNode.t), "Val"] ↦ (v.(heapexamples.TreeNode.Val')))
    (l.[(heapexamples.TreeNode.t), "Val"] ↦ Val')
    (l ↦ v) (l ↦ (v <|(heapexamples.TreeNode.Val') := Val'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance TreeNode_access_load_Left l (v : (heapexamples.TreeNode.t)) dq :
  AccessStrict
    (l.[(heapexamples.TreeNode.t), "Left"] ↦{dq} (v.(heapexamples.TreeNode.Left')))
    (l.[(heapexamples.TreeNode.t), "Left"] ↦{dq} (v.(heapexamples.TreeNode.Left')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance TreeNode_access_store_Left l (v : (heapexamples.TreeNode.t)) Left' :
  AccessStrict
    (l.[(heapexamples.TreeNode.t), "Left"] ↦ (v.(heapexamples.TreeNode.Left')))
    (l.[(heapexamples.TreeNode.t), "Left"] ↦ Left')
    (l ↦ v) (l ↦ (v <|(heapexamples.TreeNode.Left') := Left'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance TreeNode_access_load_Right l (v : (heapexamples.TreeNode.t)) dq :
  AccessStrict
    (l.[(heapexamples.TreeNode.t), "Right"] ↦{dq} (v.(heapexamples.TreeNode.Right')))
    (l.[(heapexamples.TreeNode.t), "Right"] ↦{dq} (v.(heapexamples.TreeNode.Right')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance TreeNode_access_store_Right l (v : (heapexamples.TreeNode.t)) Right' :
  AccessStrict
    (l.[(heapexamples.TreeNode.t), "Right"] ↦ (v.(heapexamples.TreeNode.Right')))
    (l.[(heapexamples.TreeNode.t), "Right"] ↦ Right')
    (l ↦ v) (l ↦ (v <|(heapexamples.TreeNode.Right') := Right'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End TreeNode.

Module ListNode.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : heapexamples.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance ListNode_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (heapexamples.ListNode.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Val" ∷ l.[(heapexamples.ListNode.t), "Val"] ↦{dq} v.(heapexamples.ListNode.Val') ∗
      "Next" ∷ l.[(heapexamples.ListNode.t), "Next"] ↦{dq} v.(heapexamples.ListNode.Next') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance ListNode_into_val_typed
   :
  IntoValTypedUnderlying (heapexamples.ListNode.t) (heapexamples.ListNodeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance ListNode_access_load_Val l (v : (heapexamples.ListNode.t)) dq :
  AccessStrict
    (l.[(heapexamples.ListNode.t), "Val"] ↦{dq} (v.(heapexamples.ListNode.Val')))
    (l.[(heapexamples.ListNode.t), "Val"] ↦{dq} (v.(heapexamples.ListNode.Val')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ListNode_access_store_Val l (v : (heapexamples.ListNode.t)) Val' :
  AccessStrict
    (l.[(heapexamples.ListNode.t), "Val"] ↦ (v.(heapexamples.ListNode.Val')))
    (l.[(heapexamples.ListNode.t), "Val"] ↦ Val')
    (l ↦ v) (l ↦ (v <|(heapexamples.ListNode.Val') := Val'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance ListNode_access_load_Next l (v : (heapexamples.ListNode.t)) dq :
  AccessStrict
    (l.[(heapexamples.ListNode.t), "Next"] ↦{dq} (v.(heapexamples.ListNode.Next')))
    (l.[(heapexamples.ListNode.t), "Next"] ↦{dq} (v.(heapexamples.ListNode.Next')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance ListNode_access_store_Next l (v : (heapexamples.ListNode.t)) Next' :
  AccessStrict
    (l.[(heapexamples.ListNode.t), "Next"] ↦ (v.(heapexamples.ListNode.Next')))
    (l.[(heapexamples.ListNode.t), "Next"] ↦ Next')
    (l ↦ v) (l ↦ (v <|(heapexamples.ListNode.Next') := Next'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End ListNode.

End heapexamples.
