(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.fmt.
Require Export New.generatedproof.io.
Require Export New.generatedproof.sort.
Require Export New.generatedproof.strings.
Require Export New.generatedproof.sync.
Require Export New.golang.theory.

Require Export New.code.btree.

Set Default Proof Using "Type".

Module btree.

(* type btree.Item *)
Module Item.

#[global] Transparent btree.Item.
#[global] Typeclasses Transparent btree.Item.
Section def.
Context `{ffi_syntax}.
Definition t := interface.t.
End def.
End Item.

(* type btree.FreeList *)
Module FreeList.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  mu' : sync.Mutex.t;
  freelist' : slice.t;
}.
End def.
End FreeList.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent btree.FreeList.
#[local] Typeclasses Transparent btree.FreeList.

Global Instance FreeList_wf : struct.Wf btree.FreeList.
Proof. apply _. Qed.

Global Instance settable_FreeList : Settable FreeList.t :=
  settable! FreeList.mk < FreeList.mu'; FreeList.freelist' >.
Global Instance into_val_FreeList : IntoVal FreeList.t :=
  {| to_val_def v :=
    struct.val_aux btree.FreeList [
    "mu" ::= #(FreeList.mu' v);
    "freelist" ::= #(FreeList.freelist' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_FreeList : IntoValTyped FreeList.t btree.FreeList :=
{|
  default_val := FreeList.mk (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_FreeList_mu : IntoValStructField "mu" btree.FreeList FreeList.mu'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_FreeList_freelist : IntoValStructField "freelist" btree.FreeList FreeList.freelist'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_FreeList mu' freelist':
  PureWp True
    (struct.make #btree.FreeList (alist_val [
      "mu" ::= #mu';
      "freelist" ::= #freelist'
    ]))%struct
    #(FreeList.mk mu' freelist').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance FreeList_struct_fields_split dq l (v : FreeList.t) :
  StructFieldsSplit dq l v (
    "Hmu" ∷ l ↦s[btree.FreeList :: "mu"]{dq} v.(FreeList.mu') ∗
    "Hfreelist" ∷ l ↦s[btree.FreeList :: "freelist"]{dq} v.(FreeList.freelist')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (FreeList.mu' v)) (btree.FreeList) "mu"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type btree.ItemIterator *)
Module ItemIterator.

#[global] Transparent btree.ItemIterator.
#[global] Typeclasses Transparent btree.ItemIterator.
Section def.
Context `{ffi_syntax}.
Definition t := func.t.
End def.
End ItemIterator.

(* type btree.items *)
Module items.

#[global] Transparent btree.items.
#[global] Typeclasses Transparent btree.items.
Section def.
Context `{ffi_syntax}.
Definition t := slice.t.
End def.
End items.

(* type btree.children *)
Module children.

#[global] Transparent btree.children.
#[global] Typeclasses Transparent btree.children.
Section def.
Context `{ffi_syntax}.
Definition t := slice.t.
End def.
End children.

(* type btree.node *)
Module node.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  items' : items.t;
  children' : children.t;
  cow' : loc;
}.
End def.
End node.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent btree.node.
#[local] Typeclasses Transparent btree.node.

Global Instance node_wf : struct.Wf btree.node.
Proof. apply _. Qed.

Global Instance settable_node : Settable node.t :=
  settable! node.mk < node.items'; node.children'; node.cow' >.
Global Instance into_val_node : IntoVal node.t :=
  {| to_val_def v :=
    struct.val_aux btree.node [
    "items" ::= #(node.items' v);
    "children" ::= #(node.children' v);
    "cow" ::= #(node.cow' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_node : IntoValTyped node.t btree.node :=
{|
  default_val := node.mk (default_val _) (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_node_items : IntoValStructField "items" btree.node node.items'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_node_children : IntoValStructField "children" btree.node node.children'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_node_cow : IntoValStructField "cow" btree.node node.cow'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_node items' children' cow':
  PureWp True
    (struct.make #btree.node (alist_val [
      "items" ::= #items';
      "children" ::= #children';
      "cow" ::= #cow'
    ]))%struct
    #(node.mk items' children' cow').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance node_struct_fields_split dq l (v : node.t) :
  StructFieldsSplit dq l v (
    "Hitems" ∷ l ↦s[btree.node :: "items"]{dq} v.(node.items') ∗
    "Hchildren" ∷ l ↦s[btree.node :: "children"]{dq} v.(node.children') ∗
    "Hcow" ∷ l ↦s[btree.node :: "cow"]{dq} v.(node.cow')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (node.items' v)) (btree.node) "items"%go.
  simpl_one_flatten_struct (# (node.children' v)) (btree.node) "children"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type btree.toRemove *)
Module toRemove.

#[global] Transparent btree.toRemove.
#[global] Typeclasses Transparent btree.toRemove.
Section def.
Context `{ffi_syntax}.
Definition t := w64.
End def.
End toRemove.

(* type btree.direction *)
Module direction.

#[global] Transparent btree.direction.
#[global] Typeclasses Transparent btree.direction.
Section def.
Context `{ffi_syntax}.
Definition t := w64.
End def.
End direction.

(* type btree.BTree *)
Module BTree.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  degree' : w64;
  length' : w64;
  root' : loc;
  cow' : loc;
}.
End def.
End BTree.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent btree.BTree.
#[local] Typeclasses Transparent btree.BTree.

Global Instance BTree_wf : struct.Wf btree.BTree.
Proof. apply _. Qed.

Global Instance settable_BTree : Settable BTree.t :=
  settable! BTree.mk < BTree.degree'; BTree.length'; BTree.root'; BTree.cow' >.
Global Instance into_val_BTree : IntoVal BTree.t :=
  {| to_val_def v :=
    struct.val_aux btree.BTree [
    "degree" ::= #(BTree.degree' v);
    "length" ::= #(BTree.length' v);
    "root" ::= #(BTree.root' v);
    "cow" ::= #(BTree.cow' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_BTree : IntoValTyped BTree.t btree.BTree :=
{|
  default_val := BTree.mk (default_val _) (default_val _) (default_val _) (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_BTree_degree : IntoValStructField "degree" btree.BTree BTree.degree'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_BTree_length : IntoValStructField "length" btree.BTree BTree.length'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_BTree_root : IntoValStructField "root" btree.BTree BTree.root'.
Proof. solve_into_val_struct_field. Qed.

Global Instance into_val_struct_field_BTree_cow : IntoValStructField "cow" btree.BTree BTree.cow'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_BTree degree' length' root' cow':
  PureWp True
    (struct.make #btree.BTree (alist_val [
      "degree" ::= #degree';
      "length" ::= #length';
      "root" ::= #root';
      "cow" ::= #cow'
    ]))%struct
    #(BTree.mk degree' length' root' cow').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance BTree_struct_fields_split dq l (v : BTree.t) :
  StructFieldsSplit dq l v (
    "Hdegree" ∷ l ↦s[btree.BTree :: "degree"]{dq} v.(BTree.degree') ∗
    "Hlength" ∷ l ↦s[btree.BTree :: "length"]{dq} v.(BTree.length') ∗
    "Hroot" ∷ l ↦s[btree.BTree :: "root"]{dq} v.(BTree.root') ∗
    "Hcow" ∷ l ↦s[btree.BTree :: "cow"]{dq} v.(BTree.cow')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.
  simpl_one_flatten_struct (# (BTree.degree' v)) (btree.BTree) "degree"%go.
  simpl_one_flatten_struct (# (BTree.length' v)) (btree.BTree) "length"%go.
  simpl_one_flatten_struct (# (BTree.root' v)) (btree.BTree) "root"%go.

  solve_field_ref_f.
Qed.

End instances.

(* type btree.copyOnWriteContext *)
Module copyOnWriteContext.
Section def.
Context `{ffi_syntax}.
Record t := mk {
  freelist' : loc;
}.
End def.
End copyOnWriteContext.

Section instances.
Context `{ffi_syntax}.
#[local] Transparent btree.copyOnWriteContext.
#[local] Typeclasses Transparent btree.copyOnWriteContext.

Global Instance copyOnWriteContext_wf : struct.Wf btree.copyOnWriteContext.
Proof. apply _. Qed.

Global Instance settable_copyOnWriteContext : Settable copyOnWriteContext.t :=
  settable! copyOnWriteContext.mk < copyOnWriteContext.freelist' >.
Global Instance into_val_copyOnWriteContext : IntoVal copyOnWriteContext.t :=
  {| to_val_def v :=
    struct.val_aux btree.copyOnWriteContext [
    "freelist" ::= #(copyOnWriteContext.freelist' v)
    ]%struct
  |}.

Global Program Instance into_val_typed_copyOnWriteContext : IntoValTyped copyOnWriteContext.t btree.copyOnWriteContext :=
{|
  default_val := copyOnWriteContext.mk (default_val _);
|}.
Next Obligation. solve_to_val_type. Qed.
Next Obligation. solve_zero_val. Qed.
Next Obligation. solve_to_val_inj. Qed.
Final Obligation. solve_decision. Qed.

Global Instance into_val_struct_field_copyOnWriteContext_freelist : IntoValStructField "freelist" btree.copyOnWriteContext copyOnWriteContext.freelist'.
Proof. solve_into_val_struct_field. Qed.


Context `{!ffi_model, !ffi_semantics _ _, !ffi_interp _, !heapGS Σ}.
Global Instance wp_struct_make_copyOnWriteContext freelist':
  PureWp True
    (struct.make #btree.copyOnWriteContext (alist_val [
      "freelist" ::= #freelist'
    ]))%struct
    #(copyOnWriteContext.mk freelist').
Proof. solve_struct_make_pure_wp. Qed.


Global Instance copyOnWriteContext_struct_fields_split dq l (v : copyOnWriteContext.t) :
  StructFieldsSplit dq l v (
    "Hfreelist" ∷ l ↦s[btree.copyOnWriteContext :: "freelist"]{dq} v.(copyOnWriteContext.freelist')
  ).
Proof.
  rewrite /named.
  apply struct_fields_split_intro.
  unfold_typed_pointsto; split_pointsto_app.

  rewrite -!/(typed_pointsto_def _ _ _) -!typed_pointsto_unseal.

  solve_field_ref_f.
Qed.

End instances.

(* type btree.freeType *)
Module freeType.

#[global] Transparent btree.freeType.
#[global] Typeclasses Transparent btree.freeType.
Section def.
Context `{ffi_syntax}.
Definition t := w64.
End def.
End freeType.

(* type btree.Int *)
Module Int.

#[global] Transparent btree.Int.
#[global] Typeclasses Transparent btree.Int.
Section def.
Context `{ffi_syntax}.
Definition t := w64.
End def.
End Int.

Section names.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context `{!globalsGS Σ}.
Context {go_ctx : GoContext}.
#[local] Transparent is_pkg_defined is_pkg_defined_pure.

Global Instance is_pkg_defined_pure_btree : IsPkgDefinedPure btree :=
  {|
    is_pkg_defined_pure_def go_ctx :=
      is_pkg_defined_pure_single btree ∧
      is_pkg_defined_pure code.fmt.fmt ∧
      is_pkg_defined_pure code.io.io ∧
      is_pkg_defined_pure code.sort.sort ∧
      is_pkg_defined_pure code.strings.strings ∧
      is_pkg_defined_pure code.sync.sync;
  |}.

#[local] Transparent is_pkg_defined_single is_pkg_defined_pure_single.
Global Program Instance is_pkg_defined_btree : IsPkgDefined btree :=
  {|
    is_pkg_defined_def go_ctx :=
      (is_pkg_defined_single btree ∗
       is_pkg_defined code.fmt.fmt ∗
       is_pkg_defined code.io.io ∗
       is_pkg_defined code.sort.sort ∗
       is_pkg_defined code.strings.strings ∗
       is_pkg_defined code.sync.sync)%I
  |}.
Final Obligation. iIntros. iFrame "#%". Qed.
#[local] Opaque is_pkg_defined_single is_pkg_defined_pure_single.

Global Instance wp_func_call_NewFreeList :
  WpFuncCall btree.NewFreeList _ (is_pkg_defined btree) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_New :
  WpFuncCall btree.New _ (is_pkg_defined btree) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_NewWithFreeList :
  WpFuncCall btree.NewWithFreeList _ (is_pkg_defined btree) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_min :
  WpFuncCall btree.min _ (is_pkg_defined btree) :=
  ltac:(solve_wp_func_call).

Global Instance wp_func_call_max :
  WpFuncCall btree.max _ (is_pkg_defined btree) :=
  ltac:(solve_wp_func_call).

Global Instance wp_method_call_FreeList'ptr_freeNode :
  WpMethodCall (ptrT.id btree.FreeList.id) "freeNode" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_FreeList'ptr_newNode :
  WpMethodCall (ptrT.id btree.FreeList.id) "newNode" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_items_find :
  WpMethodCall btree.items.id "find" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_items'ptr_find :
  WpMethodCall (ptrT.id btree.items.id) "find" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_items'ptr_insertAt :
  WpMethodCall (ptrT.id btree.items.id) "insertAt" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_items'ptr_pop :
  WpMethodCall (ptrT.id btree.items.id) "pop" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_items'ptr_removeAt :
  WpMethodCall (ptrT.id btree.items.id) "removeAt" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_items'ptr_truncate :
  WpMethodCall (ptrT.id btree.items.id) "truncate" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_children'ptr_insertAt :
  WpMethodCall (ptrT.id btree.children.id) "insertAt" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_children'ptr_pop :
  WpMethodCall (ptrT.id btree.children.id) "pop" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_children'ptr_removeAt :
  WpMethodCall (ptrT.id btree.children.id) "removeAt" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_children'ptr_truncate :
  WpMethodCall (ptrT.id btree.children.id) "truncate" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_get :
  WpMethodCall (ptrT.id btree.node.id) "get" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_growChildAndRemove :
  WpMethodCall (ptrT.id btree.node.id) "growChildAndRemove" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_insert :
  WpMethodCall (ptrT.id btree.node.id) "insert" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_iterate :
  WpMethodCall (ptrT.id btree.node.id) "iterate" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_maybeSplitChild :
  WpMethodCall (ptrT.id btree.node.id) "maybeSplitChild" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_mutableChild :
  WpMethodCall (ptrT.id btree.node.id) "mutableChild" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_mutableFor :
  WpMethodCall (ptrT.id btree.node.id) "mutableFor" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_print :
  WpMethodCall (ptrT.id btree.node.id) "print" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_remove :
  WpMethodCall (ptrT.id btree.node.id) "remove" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_reset :
  WpMethodCall (ptrT.id btree.node.id) "reset" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_node'ptr_split :
  WpMethodCall (ptrT.id btree.node.id) "split" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_Ascend :
  WpMethodCall (ptrT.id btree.BTree.id) "Ascend" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_AscendGreaterOrEqual :
  WpMethodCall (ptrT.id btree.BTree.id) "AscendGreaterOrEqual" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_AscendLessThan :
  WpMethodCall (ptrT.id btree.BTree.id) "AscendLessThan" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_AscendRange :
  WpMethodCall (ptrT.id btree.BTree.id) "AscendRange" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_Clear :
  WpMethodCall (ptrT.id btree.BTree.id) "Clear" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_Clone :
  WpMethodCall (ptrT.id btree.BTree.id) "Clone" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_Delete :
  WpMethodCall (ptrT.id btree.BTree.id) "Delete" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_DeleteMax :
  WpMethodCall (ptrT.id btree.BTree.id) "DeleteMax" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_DeleteMin :
  WpMethodCall (ptrT.id btree.BTree.id) "DeleteMin" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_Descend :
  WpMethodCall (ptrT.id btree.BTree.id) "Descend" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_DescendGreaterThan :
  WpMethodCall (ptrT.id btree.BTree.id) "DescendGreaterThan" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_DescendLessOrEqual :
  WpMethodCall (ptrT.id btree.BTree.id) "DescendLessOrEqual" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_DescendRange :
  WpMethodCall (ptrT.id btree.BTree.id) "DescendRange" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_Get :
  WpMethodCall (ptrT.id btree.BTree.id) "Get" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_Has :
  WpMethodCall (ptrT.id btree.BTree.id) "Has" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_Len :
  WpMethodCall (ptrT.id btree.BTree.id) "Len" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_Max :
  WpMethodCall (ptrT.id btree.BTree.id) "Max" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_Min :
  WpMethodCall (ptrT.id btree.BTree.id) "Min" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_ReplaceOrInsert :
  WpMethodCall (ptrT.id btree.BTree.id) "ReplaceOrInsert" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_deleteItem :
  WpMethodCall (ptrT.id btree.BTree.id) "deleteItem" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_maxItems :
  WpMethodCall (ptrT.id btree.BTree.id) "maxItems" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_BTree'ptr_minItems :
  WpMethodCall (ptrT.id btree.BTree.id) "minItems" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_copyOnWriteContext'ptr_freeNode :
  WpMethodCall (ptrT.id btree.copyOnWriteContext.id) "freeNode" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_copyOnWriteContext'ptr_newNode :
  WpMethodCall (ptrT.id btree.copyOnWriteContext.id) "newNode" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_Int_Less :
  WpMethodCall btree.Int.id "Less" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

Global Instance wp_method_call_Int'ptr_Less :
  WpMethodCall (ptrT.id btree.Int.id) "Less" _ (is_pkg_defined btree) :=
  ltac:(solve_wp_method_call).

End names.
End btree.
