(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.fmt.
Require Export New.generatedproof.io.
Require Export New.generatedproof.sort.
Require Export New.generatedproof.strings.
Require Export New.generatedproof.sync.
Require Export New.golang.theory.
Require Export New.code.github_com.google.btree.

Set Default Proof Using "Type".

Module btree.
Module FreeList.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : btree.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance FreeList_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (btree.FreeList.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "mu" ∷ l.[(btree.FreeList.t), "mu"] ↦{dq} v.(btree.FreeList.mu') ∗
      "freelist" ∷ l.[(btree.FreeList.t), "freelist"] ↦{dq} v.(btree.FreeList.freelist') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance FreeList_into_val_typed
   :
  IntoValTypedUnderlying (btree.FreeList.t) (btree.FreeListⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance FreeList_access_load_mu l (v : (btree.FreeList.t)) dq :
  AccessStrict
    (l.[(btree.FreeList.t), "mu"] ↦{dq} (v.(btree.FreeList.mu')))
    (l.[(btree.FreeList.t), "mu"] ↦{dq} (v.(btree.FreeList.mu')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance FreeList_access_store_mu l (v : (btree.FreeList.t)) mu' :
  AccessStrict
    (l.[(btree.FreeList.t), "mu"] ↦ (v.(btree.FreeList.mu')))
    (l.[(btree.FreeList.t), "mu"] ↦ mu')
    (l ↦ v) (l ↦ (v <|(btree.FreeList.mu') := mu'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance FreeList_access_load_freelist l (v : (btree.FreeList.t)) dq :
  AccessStrict
    (l.[(btree.FreeList.t), "freelist"] ↦{dq} (v.(btree.FreeList.freelist')))
    (l.[(btree.FreeList.t), "freelist"] ↦{dq} (v.(btree.FreeList.freelist')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance FreeList_access_store_freelist l (v : (btree.FreeList.t)) freelist' :
  AccessStrict
    (l.[(btree.FreeList.t), "freelist"] ↦ (v.(btree.FreeList.freelist')))
    (l.[(btree.FreeList.t), "freelist"] ↦ freelist')
    (l ↦ v) (l ↦ (v <|(btree.FreeList.freelist') := freelist'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End FreeList.

Module node.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : btree.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance node_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (btree.node.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "items" ∷ l.[(btree.node.t), "items"] ↦{dq} v.(btree.node.items') ∗
      "children" ∷ l.[(btree.node.t), "children"] ↦{dq} v.(btree.node.children') ∗
      "cow" ∷ l.[(btree.node.t), "cow"] ↦{dq} v.(btree.node.cow') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance node_into_val_typed
   :
  IntoValTypedUnderlying (btree.node.t) (btree.nodeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance node_access_load_items l (v : (btree.node.t)) dq :
  AccessStrict
    (l.[(btree.node.t), "items"] ↦{dq} (v.(btree.node.items')))
    (l.[(btree.node.t), "items"] ↦{dq} (v.(btree.node.items')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance node_access_store_items l (v : (btree.node.t)) items' :
  AccessStrict
    (l.[(btree.node.t), "items"] ↦ (v.(btree.node.items')))
    (l.[(btree.node.t), "items"] ↦ items')
    (l ↦ v) (l ↦ (v <|(btree.node.items') := items'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance node_access_load_children l (v : (btree.node.t)) dq :
  AccessStrict
    (l.[(btree.node.t), "children"] ↦{dq} (v.(btree.node.children')))
    (l.[(btree.node.t), "children"] ↦{dq} (v.(btree.node.children')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance node_access_store_children l (v : (btree.node.t)) children' :
  AccessStrict
    (l.[(btree.node.t), "children"] ↦ (v.(btree.node.children')))
    (l.[(btree.node.t), "children"] ↦ children')
    (l ↦ v) (l ↦ (v <|(btree.node.children') := children'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance node_access_load_cow l (v : (btree.node.t)) dq :
  AccessStrict
    (l.[(btree.node.t), "cow"] ↦{dq} (v.(btree.node.cow')))
    (l.[(btree.node.t), "cow"] ↦{dq} (v.(btree.node.cow')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance node_access_store_cow l (v : (btree.node.t)) cow' :
  AccessStrict
    (l.[(btree.node.t), "cow"] ↦ (v.(btree.node.cow')))
    (l.[(btree.node.t), "cow"] ↦ cow')
    (l ↦ v) (l ↦ (v <|(btree.node.cow') := cow'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End node.

Module BTree.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : btree.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance BTree_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (btree.BTree.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "degree" ∷ l.[(btree.BTree.t), "degree"] ↦{dq} v.(btree.BTree.degree') ∗
      "length" ∷ l.[(btree.BTree.t), "length"] ↦{dq} v.(btree.BTree.length') ∗
      "root" ∷ l.[(btree.BTree.t), "root"] ↦{dq} v.(btree.BTree.root') ∗
      "cow" ∷ l.[(btree.BTree.t), "cow"] ↦{dq} v.(btree.BTree.cow') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance BTree_into_val_typed
   :
  IntoValTypedUnderlying (btree.BTree.t) (btree.BTreeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance BTree_access_load_degree l (v : (btree.BTree.t)) dq :
  AccessStrict
    (l.[(btree.BTree.t), "degree"] ↦{dq} (v.(btree.BTree.degree')))
    (l.[(btree.BTree.t), "degree"] ↦{dq} (v.(btree.BTree.degree')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance BTree_access_store_degree l (v : (btree.BTree.t)) degree' :
  AccessStrict
    (l.[(btree.BTree.t), "degree"] ↦ (v.(btree.BTree.degree')))
    (l.[(btree.BTree.t), "degree"] ↦ degree')
    (l ↦ v) (l ↦ (v <|(btree.BTree.degree') := degree'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance BTree_access_load_length l (v : (btree.BTree.t)) dq :
  AccessStrict
    (l.[(btree.BTree.t), "length"] ↦{dq} (v.(btree.BTree.length')))
    (l.[(btree.BTree.t), "length"] ↦{dq} (v.(btree.BTree.length')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance BTree_access_store_length l (v : (btree.BTree.t)) length' :
  AccessStrict
    (l.[(btree.BTree.t), "length"] ↦ (v.(btree.BTree.length')))
    (l.[(btree.BTree.t), "length"] ↦ length')
    (l ↦ v) (l ↦ (v <|(btree.BTree.length') := length'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance BTree_access_load_root l (v : (btree.BTree.t)) dq :
  AccessStrict
    (l.[(btree.BTree.t), "root"] ↦{dq} (v.(btree.BTree.root')))
    (l.[(btree.BTree.t), "root"] ↦{dq} (v.(btree.BTree.root')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance BTree_access_store_root l (v : (btree.BTree.t)) root' :
  AccessStrict
    (l.[(btree.BTree.t), "root"] ↦ (v.(btree.BTree.root')))
    (l.[(btree.BTree.t), "root"] ↦ root')
    (l ↦ v) (l ↦ (v <|(btree.BTree.root') := root'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance BTree_access_load_cow l (v : (btree.BTree.t)) dq :
  AccessStrict
    (l.[(btree.BTree.t), "cow"] ↦{dq} (v.(btree.BTree.cow')))
    (l.[(btree.BTree.t), "cow"] ↦{dq} (v.(btree.BTree.cow')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance BTree_access_store_cow l (v : (btree.BTree.t)) cow' :
  AccessStrict
    (l.[(btree.BTree.t), "cow"] ↦ (v.(btree.BTree.cow')))
    (l.[(btree.BTree.t), "cow"] ↦ cow')
    (l ↦ v) (l ↦ (v <|(btree.BTree.cow') := cow'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End BTree.

Module copyOnWriteContext.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : btree.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance copyOnWriteContext_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (btree.copyOnWriteContext.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "freelist" ∷ l.[(btree.copyOnWriteContext.t), "freelist"] ↦{dq} v.(btree.copyOnWriteContext.freelist') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance copyOnWriteContext_into_val_typed
   :
  IntoValTypedUnderlying (btree.copyOnWriteContext.t) (btree.copyOnWriteContextⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance copyOnWriteContext_access_load_freelist l (v : (btree.copyOnWriteContext.t)) dq :
  AccessStrict
    (l.[(btree.copyOnWriteContext.t), "freelist"] ↦{dq} (v.(btree.copyOnWriteContext.freelist')))
    (l.[(btree.copyOnWriteContext.t), "freelist"] ↦{dq} (v.(btree.copyOnWriteContext.freelist')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance copyOnWriteContext_access_store_freelist l (v : (btree.copyOnWriteContext.t)) freelist' :
  AccessStrict
    (l.[(btree.copyOnWriteContext.t), "freelist"] ↦ (v.(btree.copyOnWriteContext.freelist')))
    (l.[(btree.copyOnWriteContext.t), "freelist"] ↦ freelist')
    (l ↦ v) (l ↦ (v <|(btree.copyOnWriteContext.freelist') := freelist'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End copyOnWriteContext.

End btree.
